### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by mfb**
Updates the sentry-php and sentry-javascript libraries.

### CODE REVIEW

**Comment by Findus23** [comment]
Thanks for the reminder. I thought about it when updating my websites, but forgot again...

I hope it is okay if I run the two updates myself instead of merging (and I'll directly use the new PHP SDK)

**Comment by Findus23** [comment]
Update has been released

**Comment by mfb** [comment]
> I hope it is okay if I run the two updates myself instead of merging (and I'll directly use the new PHP SDK)

I'm not sure this is a good idea, because the new PHP SDK requires PHP ≥ 7.1 but I _think_ Matomo works with lesser PHP versions.

**Comment by Findus23** [comment]
Thanks for the info.
I  intend this plugin only for development and testing, so this is okay for me, but I added it to the plugin.json so that there is no error when installing in PHP <7.1

**Pull request closed without merging**
